language: node_js
node_js: node
addons:
  apt:
    packages:
    - oracle-java8-installer
  chrome: stable
before_install:
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle
- export PATH=$JAVA_HOME/bin:$PATH
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:galen:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:galen:local || travis_terminate 1;
  fi
env:
  global:
  - SAUCE_USERNAME: Desire2Learn
  - secure: DJvA0W0U/k26O2GETOEf2Lz3RcBW936cdm5Nzw75h3WL2Cu6MHee/9hM69JMostWqyPnbbzUNv0swwRCY8ZPfNkboHMZQRNxrUpp9yN9zz9mrXTn/qUi5bSP41DjJO8yqvYlSGO83tKN/dnvhgwYlWmGot3oJ12XB0ItO/kb868=
